[alias]
debug = "make debug"

[build]
target = "x86_64-bare.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-bare]
runner = "just update_and_run"
